### PR TITLE
Add developer info to readme

### PR DESCRIPTION
**Pull request by mstajdohar**

### CODE REVIEW

**Comment by mstajdohar** [comment]
The `typedoc` command prints errors, but works.

```
sparrow resolwe-js$ ./node_modules/.bin/gulp typedoc
[14:10:56] Using gulpfile ~/Google Drive/Work/genialis/resolwe-js/gulpfile.js
[14:10:56] Starting 'typedoc'...
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/auth.ts(1)
 Cannot find module 'rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/base.ts(19)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/connection.ts(2)
 Cannot find module 'rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/connection.ts(262)
 Cannot find name 'Promise'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/mock.ts(1)
 Cannot find module 'rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/queryobserver.ts(1)
 Cannot find module 'rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/queryobserver.ts(2)
 Cannot find module 'immutable'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/queryobserver.ts(233)
 Cannot find name 'Promise'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resource.ts(1)
 Cannot find module 'rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/addons/permissions.ts(8)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/addons/permissions.ts(9)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/addons/permissions.ts(20)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/addons/permissions.ts(21)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/addons/permissions.ts(34)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/addons/permissions.ts(35)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/modules/knowledge_base.ts(1)
 Cannot find module 'rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/rest/collection.ts(0)
 Cannot find module 'rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/rest/data.ts(20)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/rest/data.ts(24)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/rest/data.ts(28)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/rest/descriptor_schema.ts(14)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/rest/descriptor_schema.ts(18)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/rest/file.ts(0)
 Cannot find module 'rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/rest/rest_resource.ts(0)
 Cannot find module 'rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/rest/sample.ts(0)
 Cannot find module 'rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/rest/storage.ts(17)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/rest/storage.ts(21)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/rest/storage.ts(25)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/rest/storage.ts(29)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/rest/storage.ts(33)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/rest/storage.ts(37)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/resources/rest/user.ts(1)
 Cannot find module 'rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/types/rest.ts(6)
 Cannot find module 'rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/types/utils.ts(1)
 Cannot find module 'rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/types/utils.ts(21)
 Argument of type '{}' is not assignable to parameter of type 'Feature'.
  Property 'id' is missing in type '{}'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/api/types/utils.ts(31)
 Argument of type '{}' is not assignable to parameter of type 'Feature'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/base.spec.ts(1)
 Cannot find module 'rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/base.spec.ts(27)
 Cannot find name 'it'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/base.spec.ts(33)
 Cannot find name 'jasmine'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/base.spec.ts(41)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/base.spec.ts(42)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/base.spec.ts(43)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/base.spec.ts(46)
 Cannot find name 'it'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/base.spec.ts(52)
 Cannot find name 'jasmine'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/base.spec.ts(62)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/base.spec.ts(63)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/base.ts(2)
 Cannot find module 'rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/base.ts(113)
 Cannot find name 'Promise'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/base.ts(141)
 Argument of type '{}' is not assignable to parameter of type 'T'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/base.ts(403)
 Cannot find name 'Promise'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(106)
 Cannot find name 'beforeEach'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(110)
 Cannot find name 'it'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(115)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(116)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(117)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(118)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(119)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(122)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(129)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(132)
 Cannot find name 'it'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(137)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(138)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(139)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(140)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(141)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(142)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(143)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(144)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(147)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(148)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(149)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(150)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(153)
 Cannot find name 'it'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(159)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(160)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(161)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(164)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(165)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(166)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(167)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(168)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(169)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(170)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(171)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(174)
 Cannot find name 'it'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(184)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(185)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(186)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(187)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(188)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(189)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(192)
 Cannot find name 'it'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(198)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(199)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(205)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(206)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(210)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(211)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(217)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(218)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(221)
 Cannot find name 'describe'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(297)
 Cannot find name 'it'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(305)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(306)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(311)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(312)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(317)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/components/stateful.spec.ts(318)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/services/api.ts(4)
 Cannot find module '../../api'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/shared_store/index.spec.ts(18)
 Cannot find name 'fail'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/shared_store/index.spec.ts(28)
 Cannot find name 'beforeEach'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/shared_store/index.spec.ts(32)
 Cannot find name 'it'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/shared_store/index.spec.ts(33)
 Cannot find name 'jasmine'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/shared_store/index.spec.ts(36)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/shared_store/index.spec.ts(38)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/shared_store/index.spec.ts(44)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/shared_store/index.spec.ts(45)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/shared_store/index.spec.ts(51)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/shared_store/index.spec.ts(52)
 Cannot find name 'expect'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/shared_store/index.spec.ts(58)
 Cannot find name 'expect'.


[core]
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/shared_store/index.ts(1)
 Cannot find module 'rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/shared_store/index.ts(224)
 Property 'observeOn' does not exist on type 'Dispatcher'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/shared_store/index.ts(237)
 Property 'onNext' does not exist on type 'Dispatcher'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/utils/lang.ts(12)
 Cannot find name 'Promise'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/utils/lang.ts(13)
 Cannot find name 'Promise'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/utils/lang.ts(21)
 Cannot find namespace 'Rx'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/utils/lang.ts(39)


Add developer info to readme
 Namespace '"/Users/miha/Google Drive/Work/genialis/resolwe-js/src/core/utils/immutable"' has no exported member 'Collection'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/tests/component.ts(149)
 Cannot find name 'describe'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/tests/component.ts(158)
 Cannot find name 'beforeEach'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/tests/component.ts(159)
 Cannot find name 'beforeEach'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/tests/component.ts(160)
 Cannot find name 'beforeEach'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/tests/component.ts(162)
 Cannot find name 'beforeEach'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/tests/component.ts(166)
 Cannot find name 'beforeEach'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/tests/component.ts(183)
 Cannot find name 'beforeEach'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/tests/component.ts(196)
 Cannot find name 'beforeEach'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/tests/component.ts(197)
 Cannot find name 'jasmine'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/tests/component.ts(200)
 Cannot find name 'beforeEach'.
[14:10:59] /Users/miha/Google Drive/Work/genialis/resolwe-js/src/tests/component.ts(212)
 Cannot find name 'afterEach'.
Rendering [========================================] 100%
[14:11:00] Finished 'typedoc' after 4.21 s```

**Comment by mstajdohar** [comment]
@kostko How should we handle the typedoc errors?

**Comment by kostko** [comment]
The same as they are handled in `-base` (they are ignored). This is because typedoc does not support the latest typescript.

**Comment by mstajdohar** [comment]
Obsolete

**Pull request closed without merging**
